
--Insert de datos en la tabla pais
INSERT INTO pais (nombre_pais, url_polygon_pais, codigo_pais) 
VALUES ('Colombia', 'https://raw.githubusercontent.com/PublicaMundi/MappingAPI/master/data/geojson/countries.geojson#/features/49', 'CO');


--Insert de datos en la tabla departamento
INSERT INTO departamento (url_polygon_departamento, nombre_departamento, id_pais) VALUES 
('https://example.com/polygon/amazonas', 'Amazonas', 1),
('https://example.com/polygon/antioquia', 'Antioquia', 1),
('https://example.com/polygon/arauca', 'Arauca', 1),
('https://example.com/polygon/atlantico', 'Atlántico', 1),
('https://example.com/polygon/bolivar', 'Bolívar', 1),
('https://example.com/polygon/boyaca', 'Boyacá', 1),
('https://example.com/polygon/caldas', 'Caldas', 1),
('https://example.com/polygon/caqueta', 'Caquetá', 1),
('https://example.com/polygon/casanare', 'Casanare', 1),
('https://example.com/polygon/cauca', 'Cauca', 1),
('https://example.com/polygon/cesar', 'Cesar', 1),
('https://example.com/polygon/choco', 'Chocó', 1),
('https://example.com/polygon/cordoba', 'Córdoba', 1),
('https://example.com/polygon/cundinamarca', 'Cundinamarca', 1),
('https://example.com/polygon/guainia', 'Guainía', 1),
('https://example.com/polygon/guaviare', 'Guaviare', 1),
('https://example.com/polygon/huila', 'Huila', 1),
('https://example.com/polygon/magdalena', 'Magdalena', 1),
('https://example.com/polygon/meta', 'Meta', 1),
('https://example.com/polygon/narino', 'Nariño', 1),
('https://example.com/polygon/norte_de_santander', 'Norte de Santander', 1),
('https://example.com/polygon/putumayo', 'Putumayo', 1),
('https://example.com/polygon/quindio', 'Quindío', 1),
('https://example.com/polygon/risaralda', 'Risaralda', 1),
('https://example.com/polygon/san_andres_y_providencia', 'San Andrés y Providencia', 1),
('https://example.com/polygon/santander', 'Santander', 1),
('https://example.com/polygon/sucre', 'Sucre', 1),
('https://example.com/polygon/tolima', 'Tolima', 1),
('https://example.com/polygon/valle_del_cauca', 'Valle del Cauca', 1),
('https://example.com/polygon/vaupes', 'Vaupés', 1),
('https://example.com/polygon/vichada', 'Vichada', 1);


--Insert de datos en la tabla region
INSERT INTO region (url_polygon_region, nombre_region, id_departamento) VALUES 
('https://example.com/polygon/valle_de_aburra', 'Valle de Aburrá', 2),
('https://example.com/polygon/oriental', 'Oriente', 2),
('https://example.com/polygon/norte', 'Occidente', 2),
('https://example.com/polygon/suroeste', 'Norte', 2),
('https://example.com/polygon/bajo_cauca', 'Suroeste', 2),
('https://example.com/polygon/magdalena_medio', 'Bajo Cauca', 2),
('https://example.com/polygon/nordeste', 'Magdalena Medio', 2),
('https://example.com/polygon/sureste', 'Nordeste', 2);
('https://example.com/polygon/uraba', 'Urabá', 2);


-- Región Valle de Aburrá (id_region = 1)
INSERT INTO ciudad (url_polygon_ciudad, nombre_ciudad, id_region) VALUES 
('https://example.com/polygon/barbosa', 'Barbosa', 1),
('https://example.com/polygon/bello', 'Bello', 1),
('https://example.com/polygon/caldas', 'Caldas', 1),
('https://example.com/polygon/copacabana', 'Copacabana', 1),
('https://example.com/polygon/envigado', 'Envigado', 1),
('https://example.com/polygon/itarare', 'Itagüí', 1),
('https://example.com/polygon/la_estrella', 'La Estrella', 1),
('https://example.com/polygon/medellin', 'Medellín', 1),
('https://example.com/polygon/sabaneta', 'Sabaneta', 1);

-- Región Oriente (id_region = 2)
INSERT INTO ciudad (url_polygon_ciudad, nombre_ciudad, id_region) VALUES 
('https://example.com/polygon/abejorral', 'Abejorral', 2),
('https://example.com/polygon/alejandria', 'Alejandría', 2),
('https://example.com/polygon/concepcion', 'Concepción', 2),
('https://example.com/polygon/el_carmen_de_viboral', 'El Carmen de Viboral', 2),
('https://example.com/polygon/el_peñol', 'El Peñol', 2),
('https://example.com/polygon/granada', 'Granada', 2),
('https://example.com/polygon/guarne', 'Guarne', 2),
('https://example.com/polygon/guatape', 'Guatapé', 2),
('https://example.com/polygon/la_union', 'La Unión', 2),
('https://example.com/polygon/marinilla', 'Marinilla', 2),
('https://example.com/polygon/nariño', 'Nariño', 2),
('https://example.com/polygon/san_carlos', 'San Carlos', 2),
('https://example.com/polygon/san_luis', 'San Luis', 2),
('https://example.com/polygon/san_pedro_de_los_milagros', 'San Pedro de los Milagros', 2),
('https://example.com/polygon/san_rafael', 'San Rafael', 2),
('https://example.com/polygon/san_andres_de_cuerquia', 'San Andrés de Cuerquía', 2),
('https://example.com/polygon/santuario', 'Santuario', 2),
('https://example.com/polygon/sonsón', 'Sonsón', 2);

-- Región Occidente (id_region = 3)
INSERT INTO ciudad (url_polygon_ciudad, nombre_ciudad, id_region) VALUES 
('https://example.com/polygon/abriaqui', 'Abriaquí', 3),
('https://example.com/polygon/armenia', 'Armenia', 3),
('https://example.com/polygon/cañasgordas', 'Cañasgordas', 3),
('https://example.com/polygon/dabeiba', 'Dabeiba', 3),
('https://example.com/polygon/ebejico', 'Ebéjico', 3),
('https://example.com/polygon/heliconia', 'Heliconia', 3),
('https://example.com/polygon/liborina', 'Liborina', 3),
('https://example.com/polygon/sabanalarga', 'Sabanalarga', 3),
('https://example.com/polygon/toledo', 'Toledo', 3),
('https://example.com/polygon/uramita', 'Uramita', 3);

-- Región Norte (id_region = 4)
INSERT INTO ciudad (url_polygon_ciudad, nombre_ciudad, id_region) VALUES 
('https://example.com/polygon/belmira', 'Belmira', 4),
('https://example.com/polygon/betulia', 'Betulia', 4),
('https://example.com/polygon/campamento', 'Campamento', 4),
('https://example.com/polygon/entrerríos', 'Entrerríos', 4),
('https://example.com/polygon/gomez_plata', 'Gómez Plata', 4),
('https://example.com/polygon/guadalupe', 'Guadalupe', 4),
('https://example.com/polygon/ituango', 'Ituango', 4),
('https://example.com/polygon/valdivia', 'Valdivia', 4),
('https://example.com/polygon/yarumal', 'Yarumal', 4);

-- Región Suroeste (id_region = 5)
INSERT INTO ciudad (url_polygon_ciudad, nombre_ciudad, id_region) VALUES 
('https://example.com/polygon/amaga', 'Amagá', 5),
('https://example.com/polygon/andes', 'Andes', 5),
('https://example.com/polygon/angelopolis', 'Angelópolis', 5),
('https://example.com/polygon/betania', 'Betania', 5),
('https://example.com/polygon/bolivar', 'Bolívar', 5),
('https://example.com/polygon/caramanta', 'Caramanta', 5),
('https://example.com/polygon/concordia', 'Concordia', 5),
('https://example.com/polygon/fredonia', 'Fredonia', 5),
('https://example.com/polygon/hispania', 'Hispania', 5),
('https://example.com/polygon/jardin', 'Jardín', 5),
('https://example.com/polygon/la_pintada', 'La Pintada', 5),
('https://example.com/polygon/montebello', 'Montebello', 5),
('https://example.com/polygon/pueblorrico', 'Pueblorrico', 5),
('https://example.com/polygon/salgar', 'Salgar', 5),
('https://example.com/polygon/tamesis', 'Támesis', 5),
('https://example.com/polygon/tarso', 'Tarazá', 5),
('https://example.com/polygon/titiribi', 'Titiribí', 5),
('https://example.com/polygon/valparaiso', 'Valparaíso', 5),
('https://example.com/polygon/venecia', 'Venecia', 5);

-- Región Bajo Cauca (id_region = 6)
INSERT INTO ciudad (url_polygon_ciudad, nombre_ciudad, id_region) VALUES 
('https://example.com/polygon/caucasia', 'Caucasia', 6),
('https://example.com/polygon/chigorodo', 'Chigorodó', 6),
('https://example.com/polygon/caceres', 'Cáceres', 6),
('https://example.com/polygon/nechi', 'Nechí', 6),
('https://example.com/polygon/taraza', 'Tarazá', 6),
('https://example.com/polygon/zaragoza', 'Zaragoza', 6);

-- Región Magdalena Medio (id_region = 7)
INSERT INTO ciudad (url_polygon_ciudad, nombre_ciudad, id_region) VALUES 
('https://example.com/polygon/caracoli', 'Caracolí', 7),
('https://example.com/polygon/maceo', 'Maceo', 7),
('https://example.com/polygon/puerto_berrío', 'Puerto Berrío', 7),
('https://example.com/polygon/puerto_nare', 'Puerto Nare', 7),
('https://example.com/polygon/puerto_triunfo', 'Puerto Triunfo', 7),
('https://example.com/polygon/yondo', 'Yondó', 7);

-- Región Nordeste (id_region = 8)
INSERT INTO ciudad (url_polygon_ciudad, nombre_ciudad, id_region) VALUES 
('https://example.com/polygon/anori', 'Anorí', 8),
('https://example.com/polygon/briceno', 'Briceño', 8),
('https://example.com/polygon/cisneros', 'Cisneros', 8),
('https://example.com/polygon/remedios', 'Remedios', 8),
('https://example.com/polygon/san_roque', 'San Roque', 8),
('https://example.com/polygon/segovia', 'Segovia', 8),
('https://example.com/polygon/vegachi', 'Vegachí', 8),
('https://example.com/polygon/yali', 'Yalí', 8);

-- Región Urabá (id_region = 9)
INSERT INTO ciudad (url_polygon_ciudad, nombre_ciudad, id_region) VALUES 
('https://example.com/polygon/apartado', 'Apartadó', 9),
('https://example.com/polygon/arboletes', 'Arboletes', 9),
('https://example.com/polygon/carepa', 'Carepa', 9),
('https://example.com/polygon/chigorodo', 'Chigorodó', 9),
('https://example.com/polygon/mutata', 'Mutatá', 9),
('https://example.com/polygon/necocli', 'Necoclí', 9),
('https://example.com/polygon/san_juan_de_uraba', 'San Juan de Urabá', 9),
('https://example.com/polygon/san_pedro_de_uraba', 'San Pedro de Urabá', 9),
('https://example.com/polygon/turbo', 'Turbo', 9),
('https://example.com/polygon/vigia_del_fuerte', 'Vigía del Fuerte', 9);


--Insert de datos en la tabla comuna
 INSERT INTO comuna (url_polygon_comuna, nombre_comuna, id_ciudad) VALUES 
('https://example.com/polygon/comuna_popular', 'Comuna 1 - Popular', 8),
('https://example.com/polygon/comuna_santa_cruz', 'Comuna 2 - Santa Cruz', 8),
('https://example.com/polygon/comuna_manrique', 'Comuna 3 - Manrique', 8),
('https://example.com/polygon/comuna_aranjuez', 'Comuna 4 - Aranjuez', 8),
('https://example.com/polygon/comuna_castilla', 'Comuna 5 - Castilla', 8),
('https://example.com/polygon/comuna_doce_octubre', 'Comuna 6 - Doce de Octubre', 8),
('https://example.com/polygon/comuna_robledo', 'Comuna 7 - Robledo', 8),
('https://example.com/polygon/comuna_villa_hermosa', 'Comuna 8 - Villa Hermosa', 8),
('https://example.com/polygon/comuna_buenos_aires', 'Comuna 9 - Buenos Aires', 8),
('https://example.com/polygon/comuna_candelaria', 'Comuna 10 - La Candelaria', 8),
('https://example.com/polygon/comuna_laureles_estadio', 'Comuna 11 - Laureles-Estadio', 8),
('https://example.com/polygon/comuna_america', 'Comuna 12 - La América', 8),
('https://example.com/polygon/comuna_san_javier', 'Comuna 13 - San Javier', 8),
('https://example.com/polygon/comuna_poblado', 'Comuna 14 - El Poblado', 8),
('https://example.com/polygon/comuna_guayabal', 'Comuna 15 - Guayabal', 8),
('https://example.com/polygon/comuna_belén', 'Comuna 16 - Belén', 8),
('https://example.com/polygon/comuna_palmitas', 'Comuna 50 - Palmitas', 8),
('https://example.com/polygon/comuna_san_cristobal', 'Comuna 60 - San Cristóbal', 8),
('https://example.com/polygon/comuna_altavista', 'Comuna 70 - Altavista', 8),
('https://example.com/polygon/comuna_san_antonio_prado', 'Comuna 80 - San Antonio de Prado', 8),
('https://example.com/polygon/comuna_santa_elena', 'Comuna 90 - Santa Elena', 8);


--Insert de datos en la tabla barrio
INSERT INTO barrio (url_polygon_barrio, nombre_barrio, id_comuna) VALUES 
-- Comuna 1 - Popular (id_comuna = 1)
('https://example.com/polygon/barrio_aldea_pablo_vi', 'Aldea Pablo VI', 1),
('https://example.com/polygon/barrio_carpinelo', 'Carpinelo', 1),
('https://example.com/polygon/barrio_el_compromiso', 'El Compromiso', 1),
('https://example.com/polygon/barrio_la_avanzada', 'La Avanzada', 1),
('https://example.com/polygon/barrio_la_esperanza_2', 'La Esperanza Nº 2', 1),
('https://example.com/polygon/barrio_moscu_2', 'Moscú Nº 2', 1),
('https://example.com/polygon/barrio_popular_1_2', 'Popular 1-2', 1),
('https://example.com/polygon/barrio_popular_granizal', 'Popular, Granizal', 1),
('https://example.com/polygon/barrio_san_pablo', 'San Pablo', 1),
('https://example.com/polygon/barrio_santo_domingo_sabio_1', 'Santo Domingo Sabio Nº 1', 1),
('https://example.com/polygon/barrio_santo_domingo_sabio_2', 'Santo Domingo Sabio Nº 2', 1),
('https://example.com/polygon/barrio_villa_guadalupe', 'Villa Guadalupe', 1),

-- Comuna 2 - Santa Cruz (id_comuna = 2)
('https://example.com/polygon/barrio_andalucia', 'Andalucía', 2),
('https://example.com/polygon/barrio_el_playon_de_los_comuneros', 'El Playón de Los Comuneros', 2),
('https://example.com/polygon/barrio_la_franca', 'La Francia', 2),
('https://example.com/polygon/barrio_la_frontera', 'La Frontera', 2),
('https://example.com/polygon/barrio_la_isla', 'La Isla', 2),
('https://example.com/polygon/barrio_la_rosa', 'La Rosa', 2),
('https://example.com/polygon/barrio_moscu_1', 'Moscú Nº 1', 2),
('https://example.com/polygon/barrio_pablo_vi', 'Pablo VI', 2),
('https://example.com/polygon/barrio_santa_cruz', 'Santa Cruz', 2),
('https://example.com/polygon/barrio_villa_del_socorro', 'Villa del Socorro', 2),
('https://example.com/polygon/barrio_villa_niza', 'Villa Niza', 2),

-- Comuna 3 - Manrique (id_comuna = 3)
('https://example.com/polygon/barrio_campo_valdes_2', 'Campo Valdes Nº 2', 3),
('https://example.com/polygon/barrio_el_pomar', 'El Pomar', 3),
('https://example.com/polygon/barrio_el_raizal', 'El Raizal', 3),
('https://example.com/polygon/barrio_la_cruz', 'La Cruz', 3),
('https://example.com/polygon/barrio_la_honda', 'La Honda', 3),
('https://example.com/polygon/barrio_la_salle', 'La Salle', 3),
('https://example.com/polygon/barrio_las_granjas', 'Las Granjas', 3),
('https://example.com/polygon/barrio_manrique_central_2', 'Manrique Central Nº 2', 3),
('https://example.com/polygon/barrio_manrique_oriental', 'Manrique Oriental', 3),
('https://example.com/polygon/barrio_maria_cano_carambolas', 'Maria Cano – Carambolas', 3),
('https://example.com/polygon/barrio_oriente', 'Oriente', 3),
('https://example.com/polygon/barrio_san_jose_la_cima_1', 'San José La Cima Nº 1', 3),
('https://example.com/polygon/barrio_san_jose_la_cima_2', 'San José La Cima Nº 2', 3),
('https://example.com/polygon/barrio_santa_ines', 'Santa Inés', 3),
('https://example.com/polygon/barrio_versalles_1', 'Versalles Nº 1', 3),
('https://example.com/polygon/barrio_versalles_2', 'Versalles Nº 2', 3),

-- Comuna 4 - Aranjuez (id_comuna = 4)
('https://example.com/polygon/barrio_aranjuez', 'Aranjuez', 4),
('https://example.com/polygon/barrio_berlin', 'Berlín', 4),
('https://example.com/polygon/barrio_bermejal_los_alamos', 'Bermejal - Los Álamos', 4),
('https://example.com/polygon/barrio_brasilia', 'Brasilia', 4),
('https://example.com/polygon/barrio_campo_valdes_1', 'Campo Valdes Nº 1', 4),
('https://example.com/polygon/barrio_la_pinuea', 'La Piñuela', 4),
('https://example.com/polygon/barrio_las_esmeraldas', 'Las Esmeraldas', 4),
('https://example.com/polygon/barrio_manrique_central_1', 'Manrique Central Nº 1', 4),
('https://example.com/polygon/barrio_miranda', 'Miranda', 4),
('https://example.com/polygon/barrio_moravia', 'Moravia', 4),
('https://example.com/polygon/barrio_palermo', 'Palermo', 4),
('https://example.com/polygon/barrio_san_isidro', 'San Isidro', 4),
('https://example.com/polygon/barrio_san_pedro', 'San Pedro', 4),
('https://example.com/polygon/barrio_sevilla', 'Sevilla', 4),

-- Comuna 5 - Castilla (id_comuna = 5)
('https://example.com/polygon/barrio_alfonso_lopez', 'Alfonso López', 5),
('https://example.com/polygon/barrio_belalcazar', 'Belalcazar', 5),
('https://example.com/polygon/barrio_boyaca', 'Boyacá', 5),
('https://example.com/polygon/barrio_caribe', 'Caribe', 5),
('https://example.com/polygon/barrio_castilla', 'Castilla', 5),
('https://example.com/polygon/barrio_el_progreso', 'El Progreso', 5),
('https://example.com/polygon/barrio_florencia', 'Florencia', 5),
('https://example.com/polygon/barrio_francisco_antonio_zea', 'Francisco Antonio Zea', 5),
('https://example.com/polygon/barrio_girardot', 'Girardot', 5),
('https://example.com/polygon/barrio_hector_abad_gomez', 'Héctor Abad Gómez', 5),
('https://example.com/polygon/barrio_las_brisas', 'Las Brisas', 5),
('https://example.com/polygon/barrio_tejelo', 'Tejelo', 5),
('https://example.com/polygon/barrio_toscaza', 'Toscaza', 5),
('https://example.com/polygon/barrio_tricentenario', 'Tricentenario', 5),

-- Comuna 6 - Doce de Octubre (id_comuna = 6)
('https://example.com/polygon/barrio_10_01_2001', '10/01/2001', 6),
('https://example.com/polygon/barrio_10_02_2001', '10/02/2001', 6),
('https://example.com/polygon/barrio_el_triunfo', 'El Triunfo', 6),
('https://example.com/polygon/barrio_kennedy', 'Kennedy', 6),
('https://example.com/polygon/barrio_la_esperanza', 'La Esperanza', 6),
('https://example.com/polygon/barrio_mirador_del_doce', 'Mirador del Doce', 6),
('https://example.com/polygon/barrio_pedregal', 'Pedregal', 6),
('https://example.com/polygon/barrio_picachito', 'Picachito', 6),
('https://example.com/polygon/barrio_picacho', 'Picacho', 6),
('https://example.com/polygon/barrio_progreso_2', 'Progreso Nº 2', 6),
('https://example.com/polygon/barrio_san_martin_de_porres', 'San Martín de Porres', 6),
('https://example.com/polygon/barrio_santander', 'Santander', 6),

-- Comuna 7 - Robledo (id_comuna = 7)
('https://example.com/polygon/barrio_altamira', 'Altamira', 7),
('https://example.com/polygon/barrio_aures_1', 'Aures Nº 1', 7),
('https://example.com/polygon/barrio_aures_2', 'Aures Nº 2', 7),
('https://example.com/polygon/barrio_barrio_facultad_de_minas', 'Barrio Facultad de Minas', 7),
('https://example.com/polygon/barrio_bello_horizonte', 'Bello Horizonte', 7),
('https://example.com/polygon/barrio_bosques_de_san_pablo', 'Bosques de San Pablo', 7),
('https://example.com/polygon/barrio_cerro_el_volador', 'Cerro El Volador', 7),
('https://example.com/polygon/barrio_cordoba', 'Córdoba', 7),
('https://example.com/polygon/barrio_cucaracho', 'Cucaracho', 7),
('https://example.com/polygon/barrio_el_diamante', 'El Diamante', 7),
('https://example.com/polygon/barrio_fuente_clara', 'Fuente Clara', 7),
('https://example.com/polygon/barrio_la_pilarica', 'La Pilarica', 7),
('https://example.com/polygon/barrio_lopez_de_mesa', 'López de Mesa', 7),
('https://example.com/polygon/barrio_monteclaro', 'Monteclaro', 7),
('https://example.com/polygon/barrio_nueva_villa_de_la_iguana', 'Nueva Villa de La Iguaná', 7),
('https://example.com/polygon/barrio_olaya_herrera', 'Olaya Herrera', 7),
('https://example.com/polygon/barrio_pajarito', 'Pajarito', 7),
('https://example.com/polygon/barrio_palenque', 'Palenque', 7),
('https://example.com/polygon/barrio_robledo', 'Robledo', 7),
('https://example.com/polygon/barrio_san_german', 'San Germán', 7),
('https://example.com/polygon/barrio_santa_margarita', 'Santa Margarita', 7),
('https://example.com/polygon/barrio_villa_flora', 'Villa Flora', 7),

-- Comuna 8 - Villa Hermosa (id_comuna = 8)
('https://example.com/polygon/barrio_batallon_girardot', 'Batallón Girardot', 8),
('https://example.com/polygon/barrio_el_pinal', 'El Pinal', 8),
('https://example.com/polygon/barrio_enciso', 'Enciso', 8),
('https://example.com/polygon/barrio_esfuerzos_de_paz_1', 'Esfuerzos de Paz Nº 1', 8),
('https://example.com/polygon/barrio_esfuerzos_de_paz_2', 'Esfuerzos de Paz Nº 2', 8),
('https://example.com/polygon/barrio_la_ladera', 'La Ladera', 8),
('https://example.com/polygon/barrio_la_libertad', 'La Libertad', 8),
('https://example.com/polygon/barrio_la_mansion', 'La Mansión', 8),
('https://example.com/polygon/barrio_la_sierra', 'La Sierra (Santa Lucía - Las Estancias)', 8),
('https://example.com/polygon/barrio_las_estancias', 'Las Estancias', 8),
('https://example.com/polygon/barrio_llanaditas', 'Llanaditas', 8),
('https://example.com/polygon/barrio_los_mangos', 'Los Mangos', 8),
('https://example.com/polygon/barrio_san_antonio', 'San Antonio', 8),
('https://example.com/polygon/barrio_san_miguel', 'San Miguel', 8),
('https://example.com/polygon/barrio_sucre', 'Sucre', 8),
('https://example.com/polygon/barrio_trece_de_noviembre', 'Trece de Noviembre', 8),
('https://example.com/polygon/barrio_villa_hermosa', 'Villa Hermosa', 8),
('https://example.com/polygon/barrio_villa_lilliam', 'Villa Lilliam', 8),
('https://example.com/polygon/barrio_villa_turbay', 'Villa Turbay', 8),
('https://example.com/polygon/barrio_villatina', 'Villatina', 8),

-- Comuna 9 - Buenos Aires (id_comuna = 9)
('https://example.com/polygon/barrio_alejandro_echevarria', 'Alejandro Echevarría', 9),
('https://example.com/polygon/barrio_asomadera_1', 'Asomadera Nº 1', 9),
('https://example.com/polygon/barrio_asomadera_2', 'Asomadera Nº 2', 9),
('https://example.com/polygon/barrio_asomadera_3', 'Asomadera Nº 3', 9),
('https://example.com/polygon/barrio_barrio_caicedo', 'Barrio Caicedo', 9),
('https://example.com/polygon/barrio_barrios_de_jesus', 'Barrios de Jesús', 9),
('https://example.com/polygon/barrio_bombona_2', 'Bomboná Nº 2', 9),
('https://example.com/polygon/barrio_buenos_aires', 'Buenos Aires', 9),
('https://example.com/polygon/barrio_cataluna', 'Cataluña', 9),
('https://example.com/polygon/barrio_el_salvador', 'El Salvador', 9),
('https://example.com/polygon/barrio_gerona', 'Gerona', 9),
('https://example.com/polygon/barrio_la_milagrosa', 'La Milagrosa', 9),
('https://example.com/polygon/barrio_loreto', 'Loreto', 9),
('https://example.com/polygon/barrio_los_cerros_el_vergel', 'Los Cerros El Vergel', 9),
('https://example.com/polygon/barrio_miraflores', 'Miraflores', 9),
('https://example.com/polygon/barrio_ocho_de_marzo', 'Ocho de Marzo', 9),

-- Comuna 10 - La Candelaria (id_comuna = 10)
('https://example.com/polygon/barrio_barrio_colon', 'Barrio Colón', 10),
('https://example.com/polygon/barrio_bombona_1', 'Bomboná Nº 1', 10),
('https://example.com/polygon/barrio_boston', 'Boston', 10),
('https://example.com/polygon/barrio_calle_nueva', 'Calle Nueva', 10),
('https://example.com/polygon/barrio_corazon_de_jesus', 'Corazón de Jesús', 10),
('https://example.com/polygon/barrio_el_chagualo', 'El Chagualo', 10),
('https://example.com/polygon/barrio_estacion_villa', 'Estación Villa', 10),
('https://example.com/polygon/barrio_guayaquil', 'Guayaquil', 10),
('https://example.com/polygon/barrio_jesus_nazareno', 'Jesús Nazareno', 10),
('https://example.com/polygon/barrio_la_candelaria', 'La Candelaria', 10),
('https://example.com/polygon/barrio_las_palmas', 'Las Palmas', 10),
('https://example.com/polygon/barrio_los_angeles', 'Los Ángeles', 10),
('https://example.com/polygon/barrio_perpetuo_socorro', 'Perpetuo Socorro', 10),
('https://example.com/polygon/barrio_prado', 'Prado', 10),
('https://example.com/polygon/barrio_san_benito', 'San Benito', 10),
('https://example.com/polygon/barrio_san_diego', 'San Diego', 10),
('https://example.com/polygon/barrio_villa_nueva', 'Villa Nueva', 10),

-- Comuna 11 - Laureles-Estadio (id_comuna = 11)
('https://example.com/polygon/barrio_bolivariana', 'Bolivariana', 11),
('https://example.com/polygon/barrio_carlos_e_re斯特repo', 'Carlos E. Restrepo', 11),
('https://example.com/polygon/barrio_cuarta_brigada', 'Cuarta Brigada', 11),
('https://example.com/polygon/barrio_el_velodromo', 'El Velódromo', 11),
('https://example.com/polygon/barrio_estadio', 'Estadio', 11),
('https://example.com/polygon/barrio_florida_nueva', 'Florida Nueva', 11),
('https://example.com/polygon/barrio_la_castellana', 'La Castellana', 11),
('https://example.com/polygon/barrio_las_acacias', 'Las Acacias', 11),
('https://example.com/polygon/barrio_laureles', 'Laureles', 11),
('https://example.com/polygon/barrio_lorena', 'Lorena', 11),
('https://example.com/polygon/barrio_los_colores', 'Los Colores', 11),
('https://example.com/polygon/barrio_los_conquistadores', 'Los Conquistadores', 11),
('https://example.com/polygon/barrio_naranjal', 'Naranjal', 11),
('https://example.com/polygon/barrio_san_joaquin', 'San Joaquín', 11),
('https://example.com/polygon/barrio_suramericana', 'Suramericana', 11),

-- Comuna 12 - La América (id_comuna = 12)
('https://example.com/polygon/barrio_barrio_cristobal', 'Barrio Cristóbal', 12),
('https://example.com/polygon/barrio_calasanz', 'Calasanz', 12),
('https://example.com/polygon/barrio_calasanz_parte_alta', 'Calasanz Parte Alta', 12),
('https://example.com/polygon/barrio_campo_alegre', 'Campo Alegre', 12),
('https://example.com/polygon/barrio_el_danubio', 'El Danubio', 12),
('https://example.com/polygon/barrio_ferrini', 'Ferrini', 12),
('https://example.com/polygon/barrio_la_america', 'La América', 12),
('https://example.com/polygon/barrio_la_floresta', 'La Floresta', 12),
('https://example.com/polygon/barrio_los_pinos', 'Los Pinos', 12),
('https://example.com/polygon/barrio_santa_lucia', 'Santa Lucía', 12),
('https://example.com/polygon/barrio_santa_monica', 'Santa Mónica', 12),
('https://example.com/polygon/barrio_santa_teresita', 'Santa Teresita', 12),
('https://example.com/polygon/barrio_simon_bolivar', 'Simón Bolívar', 12),

-- Comuna 13 - San Javier (id_comuna = 13)
('https://example.com/polygon/barrio_antonio_narino', 'Antonio Nariño', 13),
('https://example.com/polygon/barrio_belencito', 'Belencito', 13),
('https://example.com/polygon/barrio_betania', 'Betania', 13),
('https://example.com/polygon/barrio_blanquizal', 'Blanquizal', 13),
('https://example.com/polygon/barrio_eduardo_santos', 'Eduardo Santos', 13),
('https://example.com/polygon/barrio_el_corazon', 'El Corazón', 13),
('https://example.com/polygon/barrio_el_pesebre', 'El Pesebre', 13),
('https://example.com/polygon/barrio_el_salado', 'El Salado', 13),
('https://example.com/polygon/barrio_el_socorro', 'El Socorro', 13),
('https://example.com/polygon/barrio_juan_xiii_la_quiebra', 'Juan XIII - La Quiebra', 13),
('https://example.com/polygon/barrio_la_gabriela', 'La Gabriela', 13),
('https://example.com/polygon/barrio_la_pradera', 'La Pradera', 13),
('https://example.com/polygon/barrio_las_independencias', 'Las Independencias', 13),
('https://example.com/polygon/barrio_los_alcazares', 'Los Alcázares', 13),
('https://example.com/polygon/barrio_metropolitano', 'Metropolitano', 13),
('https://example.com/polygon/barrio_nuevos_conquistadores', 'Nuevos Conquistadores', 13),
('https://example.com/polygon/barrio_san_javier_1', 'San Javier Nº 1', 13),
('https://example.com/polygon/barrio_san_javier_2', 'San Javier Nº 2', 13),
('https://example.com/polygon/barrio_santa_rosa_de_lima', 'Santa Rosa de Lima', 13),
('https://example.com/polygon/barrio_veinte_de_julio', 'Veinte de Julio', 13),

-- Comuna 14 - El Poblado (id_comuna = 14)
('https://example.com/polygon/barrio_alejandria', 'Alejandría', 14),
('https://example.com/polygon/barrio_altos_del_poblado', 'Altos del Poblado', 14),
('https://example.com/polygon/barrio_astorga', 'Astorga', 14),
('https://example.com/polygon/barrio_barrio_colombia', 'Barrio Colombia', 14),
('https://example.com/polygon/barrio_castropol', 'Castropol', 14),
('https://example.com/polygon/barrio_el_castillo', 'El Castillo', 14),
('https://example.com/polygon/barrio_el_diamante_2', 'El Diamante Nº 2', 14),
('https://example.com/polygon/barrio_el_poblado', 'El Poblado', 14),
('https://example.com/polygon/barrio_el_tesoro', 'El Tesoro', 14),
('https://example.com/polygon/barrio_la_aguacatala', 'La Aguacatala', 14),
('https://example.com/polygon/barrio_la_florida', 'La Florida', 14),
('https://example.com/polygon/barrio_lalinde', 'Lalinde', 14),
('https://example.com/polygon/barrio_las_lomas_1', 'Las Lomas Nº 1', 14),
('https://example.com/polygon/barrio_las_lomas_2', 'Las Lomas Nº 2', 14),
('https://example.com/polygon/barrio_los_balsos_1', 'Los Balsos Nº 1', 14),
('https://example.com/polygon/barrio_los_balsos_2', 'Los Balsos Nº 2', 14),
('https://example.com/polygon/barrio_los_naranjos', 'Los Naranjos', 14),
('https://example.com/polygon/barrio_manila', 'Manila', 14),
('https://example.com/polygon/barrio_patio_bonito', 'Patio Bonito', 14),
('https://example.com/polygon/barrio_san_lucas', 'San Lucas', 14),
('https://example.com/polygon/barrio_santa_maria_de_los_angeles', 'Santa Maria de Los Ángeles', 14),
('https://example.com/polygon/barrio_simesa', 'Simesa', 14),
('https://example.com/polygon/barrio_villa_carlota', 'Villa Carlota', 14);

-- Comuna 15 - Guayabal (id_comuna = 15)
('https://example.com/polygon/barrio_campo_amor', 'Campo Amor', 15),
('https://example.com/polygon/barrio_cristo_rey', 'Cristo Rey', 15),
('https://example.com/polygon/barrio_guayabal', 'Guayabal', 15),
('https://example.com/polygon/barrio_la_colina', 'La Colina', 15),
('https://example.com/polygon/barrio_noel', 'Noel', 15),
('https://example.com/polygon/barrio_parque_juan_pablo_ii', 'Parque Juan Pablo II', 15),
('https://example.com/polygon/barrio_santa_fe', 'Santa Fe', 15),
('https://example.com/polygon/barrio_shellmar', 'Shellmar', 15),
('https://example.com/polygon/barrio_tenche', 'Tenche', 15),
('https://example.com/polygon/barrio_trinidad', 'Trinidad', 15),

-- Comuna 16 - Belén (id_comuna = 16)
('https://example.com/polygon/barrio_altavista', 'Altavista', 16),
('https://example.com/polygon/barrio_belen', 'Belén', 16),
('https://example.com/polygon/barrio_cerro_nutibara', 'Cerro Nutibara', 16),
('https://example.com/polygon/barrio_diego_echevarria', 'Diego Echevarría', 16),
('https://example.com/polygon/barrio_el_nogal_los_almendros', 'El Nogal - Los Almendros', 16),
('https://example.com/polygon/barrio_el_rincon', 'El Rincón', 16),
('https://example.com/polygon/barrio_fatima', 'Fátima', 16),
('https://example.com/polygon/barrio_granada', 'Granada', 16),
('https://example.com/polygon/barrio_la_gloria', 'La Gloria', 16),
('https://example.com/polygon/barrio_la_hondonada', 'La Hondonada', 16),
('https://example.com/polygon/barrio_la_loma_de_los_bernals', 'La Loma de Los Bernal', 16),
('https://example.com/polygon/barrio_la_mota', 'La Mota', 16),
('https://example.com/polygon/barrio_la_palma', 'La Palma', 16),
('https://example.com/polygon/barrio_las_mercedes', 'Las Mercedes', 16),
('https://example.com/polygon/barrio_las_playas', 'Las Playas', 16),
('https://example.com/polygon/barrio_las_violetas', 'Las Violetas', 16),
('https://example.com/polygon/barrio_los_alpes', 'Los Alpes', 16),
('https://example.com/polygon/barrio_miravalle', 'Miravalle', 16),
('https://example.com/polygon/barrio_nueva_villa_de_aburra', 'Nueva Villa de Aburrá', 16),
('https://example.com/polygon/barrio_rosales', 'Rosales', 16),
('https://example.com/polygon/barrio_san_bernardo', 'San Bernardo', 16);